### ISSUE TITLE
Maximo Enhancement: update additional work log types with auto-population

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16509]
CSR Response team requesting the following work log types to be auto-filled: 

NO_ACTION_FOUND
TEMP_REPAIR
NONCOA_JURISD

Also requested to consider WONUM to be auto-populated with log notes.

**Comment by ReneVarg25** [comment]
### 4/15/2024
CTM requested and will add the following:
NO_ISSUE_FOUND
Summary - No issue found.
Details - Thank you for your request. Street and Bridge Operations reviewed your request and determined 
that there is no issue found. If you have any questions regarding this request, please contact Street 
and Bridge Operations Dispatch at (512) 974-8777 and provide work order number YY-###### as a 
reference.

TEMP_REPAIR
Summary - Temporary repair completed, pending final resolution.
Details - Thank you for your request. Street and Bridge Operations has reviewed your request and a patch 
has been completed. For questions or updates, please contact our Customer Service team at (512) 
974-8777 and refer to work order number YY-######.

NONCOA_JURISD
Summary - Not in COA Jurisdiction.
Details - Thank you for your request. Street and Bridge Operations reviewed your request and determined 
that this is outside of City of Austin jurisdiction. No further action required.

**Comment by adry-martinez** [comment]
### April 17, 2024

Update TEMP_REPAIR to:
"Thank you for your request. Street and Bridge Operations completed your request and has notified the appropriate Street and Bridge Operations workgroup for follow-up, if any. If you have any questions regarding this request, please contact Street and Bridge Operations Dispatch at (512) 974-8777 and provide work order number YY-###### as a reference."

**Comment by rebekkabry** [comment]
# 5/20/24 Meeting with CTM 

- Rene has provided everything 
- On Erin's list

**Comment by rebekkabry** [comment]
# 5/22/24 Update from CTM 

- Erin updated: "I got the default work log summaries and long descriptions in TEST and PROD for the ones you requested.  I tested them out both places and all is working well!!" 

@ReneVarg25 can we Q/A this update?

**Comment by adry-martinez** [comment]
### 5/23/24
![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/d6aea721-fc2d-48c6-8289-0535d280250c)

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/5445218b-2a29-4962-9c35-cc583e1a457b)

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/a1261b15-83d6-4f85-be22-748cd003bc6e)

✅ TEMP_REPAIR
✅ NOTCOAJURS
❌ NO_ISSUE_FOUND: Notified CTM to modify details (See screenshot)

**Comment by adry-martinez** [comment]
### May 30, 2024 

Forestry would like to consider auto-populating some of their work logs.

**Comment by rebekkabry** [comment]
Erin confirmed NO_ISSUE_FOUND has been corrected. 

Erin now working on the auto fill of the WO #. YY-######, not pulling in the correct work order number. 
Nick advised it was in the progress and would complete. Working to update now.

**Comment by ReneVarg25** [comment]
### 6/10/24
NO_ISSUE_FOUND still showing details from auto population.
Currently working on script to add WO to comments instead of placeholder text. Working in Test
![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/e1fd4797-7197-4c21-bde4-fb174de14aeb)

**Comment by rebekkabry** [comment]
@ReneVarg25 confirmed log is working now. 
- These are the most commonly used on, to assist the field crew documentation. 
- There are up to 6 that have auto-fill. 

Completing and closing.
