### ISSUE TITLE
[MEETING] Maximo Discussion on UER Road Map

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#16781]
# 4/12/24
Meeting to discuss work order process improvement
Participants: Clay, Greg, Rebekka, Adry, Diana

**Comment by dianamartin** [comment]
# 4/12/24

Projects (10 projects)
- Parent WO
  - Child WO
   - material
   - labor
   - vehicle/equipment usage

Ex. Cameron Road
20 segments (Parents)
- Schedule by the day

Set performance measure
- Do 2-3 projects, gives schedule

## Proposed Process
- Parent WO - location should be set on parent
  - Child WO - street segments
  - Child WO - street segments
  - Child WO - street segments

Sidewalk asset - _service location_

**Comment by dianamartin** [comment]
@adry-martinez @rebekkabry feel free to add any meeting notes here. cc @ChristinaTremel @ReneVarg25

**Comment by adry-martinez** [comment]
## Maximo Discussion about UER Road Map
### April 12, 2024 
#### Adry's notes

Clay would like to improve CRC and Bridges process. 
Currently, CRC is using spreadsheets to track work orders. UER is set up to tell staff project statuses. 
His objective is to know project statuses: what's incoming, pending, completed and what is the cost-driver. 

CRC should be broken up to smaller issues/phases, currently they are recording on ONE work order to track a several months long projects. 

Target Finish may be considered. 
Out of 20, 2-3 child work orders/day. 
Wants to set up performance measure 

Parent - PROJECT (all Phases) by using Location, or Multiple Locations (Location 1 - 4) Actual Project Charter, Admin Costs, Inspections

Child - Phase 1 - Location 1 and multiple assets 
Child - Phase 2 - Location 2 and multiple assets
Child - Phase 3 - Location 3 and multiple assets
Child - Phase 4 - Location 4 and multiple assets

Wants report similar to UER to tell story about backlog 
will need to define what a backlog is.

Same roles and responsibilities as UER
Superintendent - conducts QA 
Supervisor - reviews and NFR 
Lead - data entry and COMP 

Brad gets work from e-mails, meetings, requests. There is no singular place to track all requests. Requesting to be done by Knack, to gather all project requirements and figure out how to move that to Maximo.

Wants concept to be also applied to Bridge. 

**Request for Project Initiation would be created in KNACK.** 

- Initial walk-through for project scope (to define what goes into MAXIMO)
- Requestor
- Location 
- Funding 
- Plans and attachments 
- Cost and estimate

There is no transparency on # of projects requested. 

DM Rivers wants to know 
PROJECTS that are in NEW (PWO)
Of a project, what are still pending? (CWO)

wants to use every status in Maximo in its proper form to pull reports from. 
wants to forecast (using target start/finish) to justify inventory management/requests 

### Maximo Ideas
I reached out to Erin A. with CTM to see whether a PM or data load would make sense for the volume of potential requests that would come in from CRC. 

She shared the following: 
_I think we could use PMs but I think for those a data load might be the easiest way to get the child work orders in.  You could create the Parent wonum and then we can have a template to enter all the child work orders in and then data load them into the system._  

Parent WONUM would reflect the Project ID and the Children would be the PROJECT ID - PHS#
For example: 

Project ID is 1234
**CRC24-1234** for **Parent** WONUM
**CRC24-1234-_PHS1_** for Child Phase 1 WONUM 
**CRC24-1234-_PHS2_** for Child Phase 2 WONUM

This concept has been used before and proved successful for the #13889

**Comment by rebekkabry** [comment]
# 10/1/25 

### Summary 
- this has been addressed throughout the year with Clay and his various supported groups to include: 
  - Bridge Maintainence and Repair 
  - Sidewalks 
  - Urban Trails 
 - We have successfully documented and improved the work order handling to match the SBO standards. 
  - Bridge Maintainence and Repair 
  - Sidewalks 
    - https://github.com/cityofaustin/atd-data-tech/issues/18899
    - https://github.com/cityofaustin/atd-data-tech/issues/18276
    - https://github.com/cityofaustin/atd-data-tech/issues/24886
  - Urban Trails 
    - https://github.com/cityofaustin/atd-data-tech/issues/21287
    - https://github.com/cityofaustin/atd-data-tech/issues/16534
    - https://github.com/cityofaustin/atd-data-tech/issues/22343

### Current Status 
- updates are all active 
- pending FME process with spatial and SW Rehab work order integration, ETA Jan 2026.

**Comment by dianamartin** [comment]
@rebekkabry 

These are the only other issues still left to do. Do we want to close this issue or keep it open until these are addressed?

**Sidewalks**
  - https://github.com/cityofaustin/atd-data-tech/issues/18899
  - https://github.com/cityofaustin/atd-data-tech/issues/24886
