### ISSUE TITLE
Boomi UAT for CSR/Knack Integration

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#25688]
It's been requested by ATS and 311 that we start meeting bi-weekly to do Boomi UAT testing for the Knack/CSR integrations. We will be meeting every Tuesday and Thursday starting on 11/18.

**Comment by ChristinaTremel** [comment]
### 11/20 Updates
- 11/18 meeting was cancelled because the API endpoint wasn't ready. 
- Started UAT testing on 11/20
- John repointed the Knack Test integration to the new Boomi Test Endpoint in AMD Data Tracker and SMD Data Tracker
- 311 sent test SRs and we did receive them in AMD Data Tracker ✅ 
-

**Comment by johnclary** [comment]
We had a VPN issue blocking us from sending activities back to 311 pres. That is resolved, and Christina created SR activities that I was able to transmit to Boomi test env after some minor upgrades to the integration.

- 25-00005049: Identify Asset, Adjust Timing
- 25-00005048: Identify Asset, Adjust Video Detection
- All of these should have an outcome code of Completed

Here's the [tracking spreadsheet](https://statics.teams.cdn.office.net/evergreen-assets/safelinks/2/atp-safelinks.html) for we're using.

**Comment by ChristinaTremel** [comment]
Paging activities are still not being received by us in Knack and troubleshooting is ongoing. Paging activities don't get closed out by AMD or SMD in Knack and SMD currently has them filtered out of the front end view. As of today, we don't anticipate this being a blocker for the January 6th go live. 

I've given updates to AMD and SMD in sprint reviews about this project and sent an email to AMD and SMD staff on 1/5 letting them know we will be going live tomorrow from 9am-11am / what to expect.
